// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    abilities: string;
    caption: string;
    img: string;
    info: string;
    labelWrap: string;
    name: string;
    root: string;
    statWrap: string;
    stats: string;
}
export const cssExports: CssExports;
export default cssExports;
