// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'teamR': string;
  'text': string;
  'text404': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
